"use client";
import {useMemo,useState} from "react";
type Video={videoId:string;title:string;thumbnail?:string;publishedTimeText?:string;lengthSeconds?:number;views?:number;url:string};
type SearchResponse={channel?:{title?:string};videos:Video[];cursorNext?:string;error?:string};
const duration=(n?:number)=>{if(n==null)return "";const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`};
const esc=(s:string)=>`"${s.replaceAll('"','""')}"`;
export default function Home(){
 const[channelUrl,setChannelUrl]=useState(""),[keyword,setKeyword]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[filter,setFilter]=useState("videos_latest"),[videos,setVideos]=useState<Video[]>([]),[cursor,setCursor]=useState<string>(),[channelTitle,setChannelTitle]=useState(""),[loading,setLoading]=useState(false),[downloading,setDownloading]=useState<string>(),[error,setError]=useState("");
 const results=useMemo(()=>{const q=keyword.trim().toLowerCase();return videos.filter(v=>!q||v.title.toLowerCase().includes(q))},[videos,keyword]);
 async function search(more=false){if(!channelUrl.trim()){setError("Enter a YouTube channel URL.");return}setLoading(true);setError("");try{const p=new URLSearchParams({channel:channelUrl.trim(),filter});if(keyword.trim())p.set("keyword",keyword.trim());if(more&&cursor)p.set("cursor",cursor);const r=await fetch(`/api/videos?${p}`);const d:SearchResponse=await r.json();if(!r.ok)throw Error(d.error||"Request failed");setChannelTitle(d.channel?.title||"");setVideos(v=>more?[...v,...d.videos]:d.videos);setCursor(d.cursorNext)}catch(e){setError(e instanceof Error?e.message:"Something went wrong") }finally{setLoading(false)}}
 async function download(v:Video){setDownloading(v.videoId);setError("");try{const r=await fetch(`/api/download?videoId=${encodeURIComponent(v.videoId)}`);if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||"Download failed")}const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`${v.title.replace(/[<>:"/\\|?*]+/g,"_").slice(0,120)||v.videoId}.mp4`;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){setError(e instanceof Error?e.message:"Download failed")}finally{setDownloading(undefined)}}
 async function copyAll(){await navigator.clipboard.writeText(results.map(v=>v.url).join("\n"))}
 function csv(){const rows=[["Title","URL","Published","Views","Duration"],...results.map(v=>[v.title,v.url,v.publishedTimeText||"",String(v.views??""),duration(v.lengthSeconds)])].map(r=>r.map(esc).join(",")).join("\n");const b=new Blob([rows],{type:"text/csv"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="youtube-videos.csv";a.click();URL.revokeObjectURL(u)}
 return <main className="shell"><section className="hero"><span className="badge">YOUTUBE CHANNEL FINDER</span><h1>Find the videos you need.</h1><p>Search a channel, filter results, copy URLs, export CSV, and test video downloads.</p></section><section className="panel"><label>Channel URL</label><input value={channelUrl} onChange={e=>setChannelUrl(e.target.value)} placeholder="https://www.youtube.com/@WWE"/><div className="grid"><div className="wide"><label>Keyword</label><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="match, championship, etc."/></div><div><label>Content</label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="videos_latest">Videos</option><option value="shorts_latest">Shorts</option><option value="streams_latest">Live streams</option></select></div><div><label>From</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label>To</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div><div className="actions"><button className="primary" onClick={()=>search(false)} disabled={loading}>{loading?"Searching…":"Search"}</button><button onClick={copyAll} disabled={!results.length}>Copy URLs</button><button onClick={csv} disabled={!results.length}>Export CSV</button></div>{error&&<div className="error">{error}</div>}</section>{channelTitle&&<div className="resultHead"><div><span className="muted">Channel</span><h2>{channelTitle}</h2></div><strong>{results.length} results</strong></div>}<section className="results">{results.map(v=><article className="video" key={v.videoId}><img src={v.thumbnail||`https://i.ytimg.com/vi/${v.videoId}/mqdefault.jpg`} alt=""/><div><h3>{v.title}</h3><div className="meta">{v.publishedTimeText||"Unknown date"}{v.views!=null?` · ${v.views.toLocaleString()} views`:""}{v.lengthSeconds!=null?` · ${duration(v.lengthSeconds)}`:""}</div><div className="url">{v.url}</div><div className="videoActions"><a href={v.url} target="_blank" rel="noreferrer">Open</a><button onClick={()=>navigator.clipboard.writeText(v.url)}>Copy</button><button className="download" onClick={()=>download(v)} disabled={downloading===v.videoId}>{downloading===v.videoId?"Preparing…":"Download"}</button></div></div></article>)}{!loading&&channelTitle&&!results.length&&<div className="empty">No videos matched.</div>}{cursor&&<button className="loadMore" onClick={()=>search(true)} disabled={loading}>{loading?"Loading…":"Load more"}</button>}</section><footer>Temporary test build. The RapidAPI key is hardcoded server-side for this temporary version.</footer></main>
}
